# Generated by Django 5.0.6 on 2024-07-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('field', models.CharField(max_length=100)),
                ('measurement', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
            ],
        ),
    ]
